version: '3'
services:
  kafka:
    image: moeenz/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9093:9093"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=kafka
      - KRAFT_CREATE_TOPICS=mltopic, predtopic
      - KRAFT_PARTITIONS_PER_TOPIC=1
    healthcheck:
      test:  [ 'CMD-SHELL', './bin/kafka-topics.sh --bootstrap-server localhost:9092 --list' ]
      interval: 5s
      timeout: 15s
      retries: 10

  ui:
    image: provectuslabs/kafka-ui:v0.4.0
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_NAME=mlcluster

  producer:
      command: python -u producer.py
      image: producer:latest
      container_name: producer
      build:
        dockerfile: Dockerfile
      depends_on:
        kafka:
          condition: service_healthy
      environment:
        - KAFKA_SERVERS=kafka:9092
      restart: always

  consumer:
      command: python -u consumer.py
      image: consumer:latest
      container_name: consumer
      build:
        dockerfile: Dockerfile
      depends_on:
        - producer
      environment:
        - KAFKA_SERVERS=kafka:9092
      restart: always